// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZAdcRKTmzASiPZ8CpUQYPwgsbgeU7go',
    appId: '1:824435455:web:bef48aab45ed589224a2ca',
    messagingSenderId: '824435455',
    projectId: 'circular-shield-441214-s8',
    authDomain: 'circular-shield-441214-s8.firebaseapp.com',
    storageBucket: 'circular-shield-441214-s8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2LWNwcMIUVWK6jCcJsIB554KoCzdQ6zQ',
    appId: '1:824435455:android:3b326d2e134edd9624a2ca',
    messagingSenderId: '824435455',
    projectId: 'circular-shield-441214-s8',
    storageBucket: 'circular-shield-441214-s8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjn_uwwAj11T9IuIHUlHPjXrbV8SDFRVE',
    appId: '1:824435455:ios:efa8e16d66aeeb0124a2ca',
    messagingSenderId: '824435455',
    projectId: 'circular-shield-441214-s8',
    storageBucket: 'circular-shield-441214-s8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication12',
  );
}
